export { productCreateRouter } from './create'
export { showProductRouter } from './show'
export { listProductRouter } from './list'
export { updateProductRouter } from './update'
export { updateProductAdminRouter } from './update-admin'